### ISSUE TITLE
Set up .env file for default environment variables.

### ISSUE THREAD

**Issue by mickohanlon23** [ccsm-cds-tools/ccsm-cds-dashboard#13]

**Comment by yunwwang** [comment]
Question is if we want .env file to be included in git commit. Currently, the file is ignored.

**Comment by mickohanlon23** [comment]
Could it be committed with some defaults? Or even committed with default values but commented out?

Right now there are default values buried in https://github.com/ccsm-cds-tools/ccsm-cds-dashboard/blob/pilot/src/smart/LaunchSmart.js#L8-L11. I think it could be helpful to see in one place what all of the configurable environment variables are.

**Comment by yunwwang** [comment]
I think we can document all the environment parameters in README or Wiki. The code segment you mentioned are variables used by SMART launch sequence. There are other variables. There are some git parameters that could help but have there limitations. Here are two commands:
* Using `.gitignore`: This is the most common solution to exclude a file from `git status`. It applies the remote and all local repos. The limit is that it does not work on existing files. So if the .env is checked in, then changes are tracked by `git status` no matter if the file is in `.gitignore`. 
* Using `skip-worktree`: This is a pretty new solution. It add a file to "do not track" list independent from `.gitignore`.  So developer does not need to exclude .env from each commit. The limit is that the change is local so that every developer need to run this command once.

We have three options
* check-in .env file and run `skip-worktree` on each local repo.
* check-in .env file and manually exclude the file from `git commit`
* leave .env file locally, add to `.gitignore`, and document all possible parameters in READ.me

**Comment by mickohanlon23** [comment]
@yunwwang I like option 3! Would you mind taking a stab at adding a README section to document the configurable ENV variable parameters, and putting up a PR for this?

**Comment by yunwwang** [comment]
https://github.com/ccsm-cds-tools/ccsm-cds-dashboard/wiki/Environment-Setting-for-Dashboard

**Comment by mickohanlon23** [comment]
Link to new Wiki page added in https://github.com/ccsm-cds-tools/ccsm-cds-dashboard/pull/19.

**Comment by mickohanlon23** [comment]
We took the approach of the 3rd option @yunwwang laid out, and included a Wiki page describing the configurable environment variables as well as a link to that wiki page in the README.
